### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [FabricMC/yarn#1468]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self

**Comment by TheoBuzz** [comment]
bye

**Comment by shedaniel** [comment]
yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes

**Comment by TheoBuzz** [comment]
you are poo face

**Comment by shedaniel** [comment]
How does one report a user for harassment and death threats

**Comment by Yoghurt4C** [comment]
:ant:
